apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlines
  namespace: povsim
  labels:
    app: airlines
    {{- include "pov-sim.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.airlines.replicas }}
  selector:
    matchLabels:
      app: airlines
  template:
    metadata:
      labels:
        app: airlines
    spec:
      containers:
        - name: airlines
          image: "{{ .Values.airlines.image.repository }}:{{ .Values.airlines.image.tag }}"
          imagePullPolicy: {{ .Values.airlines.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.airlines.port }}
          env:
            - name: PYROSCOPE_APPLICATION_NAME
              value: airlines
            - name: PYROSCOPE_SERVER_ADDRESS
              value: https://profiles-prod-026.grafana.net:443
            - name: PYROSCOPE_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-profiles-grafana-k8s-monitoring
                  key: username
            - name: PYROSCOPE_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-profiles-grafana-k8s-monitoring
                  key: password
