apiVersion: v1
kind: Service
metadata:
  name: flights
  namespace: povsim
  labels:
    app: flights
    {{- include "pov-sim.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: flights
  ports:
    - port: {{ .Values.flights.port }}
      targetPort: {{ .Values.flights.port }}
